### PR TITLE
Rework the Module and add Build/Upload Script

### LINKED ISSUE #2: Scripts for Including Packages in Conda Channel
We need to curate the recipes in this module and prepare to consolidate anything needed for `hutch-python` into one conda channel, `pcds-tag`, so that we can curate the versions of external modules that will not exist in the `default` or `conda-forge` channels.

- `pyepics`
- `pyca`
- `epics-base`
- `pydm`

We can consider doing something automatically with CI tools to update and push these to our channel, but it's unclear how necessary this will be.

### PR DESCRIPTION
**Pull request by ZLLentz**
The motivation here is to populate the `pcds-tag` channel with any packages that we'd need to use in the deployment environment that are not available in `conda-forge`, or that we should be building ourselves for whatever reason. It will then be possible to install any package from pcds with only `pcds-tag`, `defaults`, and `conda-forge`.

closes #2 

# Changes:
- Create `build.py` based on nsls-ii's build scripts. This is an extremely simple version of tools from other groups that checks which packages need to be built, builds them, and uploads them to an anaconda channel.
- Deprecate recipes for packages that I cannot support or guarantee the build for
- Update recipes to match versions we've been using in production

### CODE REVIEW

**Comment by teddyrendahl** [comment]
Nice man! This will be sweet. A few thoughts.

1.  Might be nice to put in a few lines in the `README` about how to add a package. Looks like adding a folder with the recipe then adding to `packages`. Simple enough but worth saying explicitly.
2. Tempted to put the recipes you deleted just in a `deprecated` folder for future reference. I guess we can always go back and get them from the `git` history if we decide to revive them. Not sure on this one.
3. I'm a little nervous about the `conda-forge` versions of bluesky and ophyd. I just don't think they are officially sanctioned by NSLS-II and I don't want to get screwed by somebody doing something weird there.

**Comment by ZLLentz** [comment]
1. I agree, I should expand the documentation here.
2. In `git` I trust
3. I'd rather just let CJ maintain the `conda-forge` recipes and not have to do it myself.

**Comment by teddyrendahl** [comment]
Sounds like we are in agreement. After typing it I realized that we are protected in production as long as we check every time we update `pcds-envs`.  The only thing this really risks is having some tests fail.

**Review by teddyrendahl — APPROVED** [review]
Nice! Just curious. Why not build on `Travis` after a merge? Why do we do it manually from `psbuild`? Just concerns about the architecture?

**Comment by ZLLentz** [comment]
I can give that a go of course, I just didn't get that far.

**Comment by teddyrendahl** [comment]
Thats why I said just curious. Doing it another PR is fine.

**Pull request merged**
